export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_ERRORS = 'GET_ERRORS';

export const ROOMS_HAS_ERRORED = 'ROOMS_HAS_ERRORED';
export const ROOMS_IS_LOADING = 'ROOMS_IS_LOADING';
export const ROOMS_FETCH_DATA_SUCCESS = 'ROOMS_FETCH_DATA_SUCCESS';
export const UPDATE_ROOMS = 'UPDATE_ROOMS';
export const UPDATE_ROOMS_SUCCESS = 'UPDATE_ROOMS_SUCCESS';
export const UPDATE_ROOMS_ERRORS = 'UPDATE_ROOMS_ERRORS';
export const ADD_ROOMS = 'ADD_ROOMS';
export const ADD_ROOMS_SUCCESS = 'ADD_ROOMS_SUCCESS';
export const ADD_ROOMS_ERRORS = 'ADD_ROOMS_ERRORS';
export const DELETE_ROOMS = 'DELETE_ROOMS';
export const DELETE_ROOMS_SUCCESS = 'DELETE_ROOMS_SUCCESS';
export const DELETE_ROOMS_ERRORS = 'DELETE_ROOMS_ERRORS';

export const BOOKING_HAS_ERRORED = 'BOOKING_HAS_ERRORED';
export const BOOKING_IS_LOADING = 'BOOKING_IS_LOADING';
export const BOOKING_FETCH_DATA_SUCCESS = 'BOOKING_FETCH_DATA_SUCCESS';
export const UPDATE_BOOKING = 'UPDATE_BOOKING';
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS';
export const UPDATE_BOOKING_ERRORS = 'UPDATE_BOOKING_ERRORS';
export const ADD_BOOKING = 'ADD_BOOKING';
export const ADD_BOOKING_SUCCESS = 'ADD_BOOKING_SUCCESS';
export const ADD_BOOKING_ERRORS = 'ADD_BOOKING_ERRORS';
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS';
export const DELETE_BOOKING_ERRORS = 'DELETE_BOOKING_ERRORS';